---
 PARAMETERS:
  #TasaActivacionEscalonada: [True, False]  
  NSubPoblaciones: [3]
  SubPob_Replace_Type: ['reemplazo_padre']
  Obj2Sigmod: [True, False]
  SigmLambda: [0.5, 1.5, 15.0]
  #NObjetivos: [2,3]
  #Obj2Sigmod: [True]
  NTests: [3]
  NObjetivos: [3]
  SigmaShare: [0.005, 0.015]
  

 DEPENDENCIAS:
  Obj2Sigmod: ['SigmLambda']
  NSubPoblaciones: ['SubPob_Replace_Type']  
